"""initial_tables

Revision ID: 351d0da55ee1
Revises: 
Create Date: 2026-06-26 21:16:39.537738
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '351d0da55ee1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.Enum('book', 'rss'), nullable=False),
    sa.Column('remote_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'downloading', 'completed', 'failed'), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_collection_remote_id', 'collection', ['remote_id', 'source_type'], unique=True)
    op.create_index('idx_collection_status', 'collection', ['status'], unique=False)
    op.create_table('device_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('auth_token', sa.String(length=200), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('last_connected_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('online', 'offline', 'unknown'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.Enum('book', 'rss'), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_icon', sa.String(length=500), nullable=True),
    sa.Column('source_group', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('enabled_explore', sa.Boolean(), nullable=True),
    sa.Column('has_login', sa.Boolean(), nullable=True),
    sa.Column('login_url', sa.Text(), nullable=True),
    sa.Column('login_check_js', sa.Text(), nullable=True),
    sa.Column('login_ui', sa.Text(), nullable=True),
    sa.Column('book_source_type', sa.Integer(), nullable=True),
    sa.Column('book_url_pattern', sa.Text(), nullable=True),
    sa.Column('search_url', sa.String(length=1000), nullable=True),
    sa.Column('explore_url', sa.Text(), nullable=True),
    sa.Column('explore_screen', sa.Text(), nullable=True),
    sa.Column('cover_decode_js', sa.Text(), nullable=True),
    sa.Column('event_listener', sa.Boolean(), nullable=True),
    sa.Column('custom_button', sa.Boolean(), nullable=True),
    sa.Column('rule_search', sa.Text(), nullable=True),
    sa.Column('rule_toc', sa.Text(), nullable=True),
    sa.Column('rule_explore', sa.Text(), nullable=True),
    sa.Column('rule_content', sa.Text(), nullable=True),
    sa.Column('rule_book_info', sa.Text(), nullable=True),
    sa.Column('rss_type', sa.Integer(), nullable=True),
    sa.Column('rule_articles', sa.Text(), nullable=True),
    sa.Column('rule_title', sa.Text(), nullable=True),
    sa.Column('rule_image', sa.Text(), nullable=True),
    sa.Column('rule_link', sa.Text(), nullable=True),
    sa.Column('rule_next_page', sa.Text(), nullable=True),
    sa.Column('rule_pub_date', sa.Text(), nullable=True),
    sa.Column('rule_description', sa.Text(), nullable=True),
    sa.Column('domain_key', sa.String(length=200), nullable=True),
    sa.Column('last_test_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_status', sa.Enum('pass', 'fail', 'timeout', 'error', 'untested'), nullable=True),
    sa.Column('last_test_stage', sa.String(length=20), nullable=True),
    sa.Column('test_detail', sa.JSON(), nullable=True),
    sa.Column('last_fix_detail', sa.JSON(), nullable=True),
    sa.Column('respond_time', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('test_mode', sa.Enum('jar', 'device', 'compare'), nullable=True),
    sa.Column('device_jar_diff', sa.JSON(), nullable=True),
    sa.Column('jar_optimization_count', sa.Integer(), nullable=True),
    sa.Column('last_jar_diff', sa.DateTime(), nullable=True),
    sa.Column('source_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_book_source_type', 'source', ['book_source_type'], unique=False)
    op.create_index('idx_domain_key', 'source', ['domain_key'], unique=False)
    op.create_index('idx_domain_type', 'source', ['domain_key', 'source_type'], unique=False)
    op.create_index('idx_enabled', 'source', ['enabled'], unique=False)
    op.create_index('idx_last_test_at', 'source', ['last_test_at'], unique=False)
    op.create_index('idx_rss_type', 'source', ['rss_type'], unique=False)
    op.create_index('idx_source_group', 'source', ['source_group'], unique=False, mysql_length=100)
    op.create_index('idx_source_type', 'source', ['source_type'], unique=False)
    op.create_index('idx_source_url', 'source', ['source_url'], unique=False)
    op.create_index('idx_test_status', 'source', ['last_test_status'], unique=False)
    op.create_table('debug_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=True),
    sa.Column('trigger', sa.Enum('ai', 'web', 'cli'), nullable=True),
    sa.Column('stage', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('pass', 'fail', 'timeout', 'error'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('search_status', sa.Enum('pass', 'fail', 'skip'), nullable=True),
    sa.Column('detail_status', sa.Enum('pass', 'fail', 'skip'), nullable=True),
    sa.Column('toc_status', sa.Enum('pass', 'fail', 'skip'), nullable=True),
    sa.Column('content_status', sa.Enum('pass', 'fail', 'skip'), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('test_mode', sa.Enum('jar', 'device', 'compare'), nullable=True),
    sa.Column('device_jar_diff', sa.JSON(), nullable=True),
    sa.Column('fix_applied', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_debug_created_at', 'debug_result', ['created_at'], unique=False)
    op.create_index('idx_debug_source_id', 'debug_result', ['source_id'], unique=False)
    op.create_index('idx_debug_status', 'debug_result', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_debug_status', table_name='debug_result')
    op.drop_index('idx_debug_source_id', table_name='debug_result')
    op.drop_index('idx_debug_created_at', table_name='debug_result')
    op.drop_table('debug_result')
    op.drop_index('idx_test_status', table_name='source')
    op.drop_index('idx_source_url', table_name='source')
    op.drop_index('idx_source_type', table_name='source')
    op.drop_index('idx_source_group', table_name='source', mysql_length=100)
    op.drop_index('idx_rss_type', table_name='source')
    op.drop_index('idx_last_test_at', table_name='source')
    op.drop_index('idx_enabled', table_name='source')
    op.drop_index('idx_domain_type', table_name='source')
    op.drop_index('idx_domain_key', table_name='source')
    op.drop_index('idx_book_source_type', table_name='source')
    op.drop_table('source')
    op.drop_table('device_config')
    op.drop_index('idx_collection_status', table_name='collection')
    op.drop_index('idx_collection_remote_id', table_name='collection')
    op.drop_table('collection')
    # ### end Alembic commands ###
